In [1]:
import numpy as np
import pandas as pd

In [2]:
delivery_data = pd.read_csv('deliveries.csv')
delivery_data.sample()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
155203,7914,1,Mumbai Indians,Rajasthan Royals,9,1,Ishan Kishan,AS Yadav,BA Stokes,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [3]:
imdb_data = pd.read_csv('imdb-top-1000.csv')
imdb_data.sample()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
59,Avengers: Endgame,2019,181,Action,8.4,Anthony Russo,Joe Russo,809955,858373000.0,78.0

### .groupby() 

It is used to group data based on one or more columns and perform aggregate, transformation, or filtering operations.

- **Syntax**

        df.groupby(by=None, axis=0)

| Parameter   | Description                                              | Default | Possible Values                          |
|-------------|----------------------------------------------------------|---------|------------------------------------------|
| by          | Column(s) or key(s) to group by                          | None    | label, list, function, Series            |
| axis        | Axis along which grouping is performed                   | 0       | 0 (rows), 1 (columns)                    |
| level       | Group by a specific level (for MultiIndex)               | None    | int or level name                        |
| as_index    | Return grouped labels as index                           | True    | True, False                              |
| sort        | Sort group keys                                          | True    | True, False                              |
| group_keys  | Include group keys in result index                       | True    | True, False                              |
| observed    | Show only observed values (for categorical data)         | False   | True, False                              |
| dropna      | Exclude NA values from group keys                        | True    | True, False                              |

In [4]:
grouped_genre_data = imdb_data.groupby(by=['Genre'])
grouped_genre_data

### Common Functions with `.groupby()`

These functions are typically used after applying `.groupby()`:

---

#### Aggregate Functions (reduce data)

| Function | Description                          |
|----------|--------------------------------------|
| sum()    | Sum of values in each group          |
| mean()   | Average of each group                |
| median() | Median value                         |
| min()    | Minimum value                        |
| max()    | Maximum value                        |
| count()  | Count of non-null values             |
| size()   | Total size of group (including NaN)  |
| std()    | Standard deviation                   |
| var()    | Variance                             |
| agg()    | Apply multiple aggregate functions   |

---

#### Transformation Functions (same shape output)

| Function    | Description                                      |
|-------------|--------------------------------------------------|
| transform() | Apply function and return same shape output      |
| cumcount()  | Number each item in group                        |
| cumsum()    | Cumulative sum within group                      |
| cummax()    | Cumulative maximum                               |
| cummin()    | Cumulative minimum                               |
| rank()      | Rank within each group                           |

---

#### Filter Function

| Function | Description                                  |
|----------|----------------------------------------------|
| filter() | Filter groups based on condition              |

---

In [6]:
grouped_genre_data.mean() #does not work on str dtype

TypeError: agg function failed [how->mean,dtype->object]

In [7]:
grouped_genre_data.sum() # if str, then added, otherwise addition performed for int and float dtype

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0
Biography,Schindler's ListGoodfellasHamiltonThe Intoucha...,1993199020202011200220171995198420182013201320...,11970,698.6,Steven SpielbergMartin ScorseseThomas KailOliv...,Liam NeesonRobert De NiroLin-Manuel MirandaÉri...,24006844,8.276358e+09,6023.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0
Crime,The GodfatherThe Godfather: Part II12 Angry Me...,1972197419571994200219991995199120192006199519...,13524,857.8,Francis Ford CoppolaFrancis Ford CoppolaSidney...,Marlon BrandoAl PacinoHenry FondaJohn Travolta...,33533615,8.452632e+09,6706.0
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Family,E.T. the Extra-TerrestrialWilly Wonka & the Ch...,19821971,215,15.6,Steven SpielbergMel Stuart,Henry ThomasGene Wilder,551221,4.391106e+08,158.0
Fantasy,Das Cabinet des Dr. CaligariNosferatu,19201922,170,16.0,Robert WieneF.W. Murnau,Werner KraussMax Schreck,146222,7.827267e+08,0.0
Film-Noir,The Third ManThe Maltese FalconShadow of a Doubt,194919411943,312,23.9,Carol ReedJohn HustonAlfred Hitchcock,Orson WellesHumphrey BogartTeresa Wright,367215,1.259105e+08,287.0
Horror,PsychoAlienThe ThingThe ExorcistNight of the L...,19601979198219731968196120171978193320042001,1123,87.0,Alfred HitchcockRidley ScottJohn CarpenterWill...,Anthony PerkinsSigourney WeaverKurt RussellEll...,3742556,1.034649e+09,880.0
Mystery,MementoRear WindowVertigoShutter IslandKahaani...,200019541958201020121995197219381988201219981997,1429,95.7,Christopher NolanAlfred HitchcockAlfred Hitchc...,Guy PearceJames StewartJames StewartLeonardo D...,4203004,1.256417e+09,633.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,1.755074e+07,81.0
Western,"Il buono, il brutto, il cattivoOnce Upon a Tim...",1966196819651976,593,33.4,Sergio LeoneSergio LeoneSergio LeoneClint East...,Clint EastwoodHenry FondaClint EastwoodClint E...,1289665,5.822151e+07,313.0

In [8]:
grouped_genre_data.min() # min of each feature, group wise

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,300,1924,45,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,33.0
Adventure,2001: A Space Odyssey,1925,88,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,41.0
Animation,Akira,1940,71,7.6,Adam Elliot,Adrian Molina,25229,128985.0,61.0
Biography,12 Years a Slave,1928,93,7.6,Adam McKay,Adrien Brody,27254,21877.0,48.0
Comedy,(500) Days of Summer,1921,68,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,45.0
Crime,12 Angry Men,1931,80,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,47.0
Drama,1917,1925,64,7.6,Aamir Khan,Abhay Deol,25088,3600.0,28.0
Family,E.T. the Extra-Terrestrial,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [9]:
grouped_genre_data.max() #max of each feature group wise

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Yôjinbô,2019,321,9.0,Zack Snyder,Yun-Fat Chow,2303232,936662225.0,98.0
Adventure,Zombieland,PG,228,8.6,Ömer Faruk Sorak,Yves Montand,1512360,874211619.0,100.0
Animation,Ôkami kodomo no Ame to Yuki,2020,137,8.6,Yoshifumi Kondô,Yôji Matsuda,999790,873839108.0,96.0
Biography,Zerkalo,2020,209,8.9,Tom McCarthy,Éric Toledano,1213505,753585104.0,97.0
Comedy,Zindagi Na Milegi Dobara,2020,188,8.6,Zoya Akhtar,Ömer Faruk Sorak,939631,886752933.0,99.0
Crime,À bout de souffle,2019,229,9.2,Yavuz Turgul,Vincent Cassel,1826188,790482117.0,100.0
Drama,Zwartboek,2020,242,9.3,Çagan Irmak,Çetin Tekindor,2343110,924558264.0,100.0
Family,Willy Wonka & the Chocolate Factory,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Nosferatu,1922,94,8.1,Robert Wiene,Werner Krauss,88794,445151978.0,NaN
Film-Noir,The Third Man,1949,108,8.1,John Huston,Teresa Wright,158731,123353292.0,97.0
Horror,The Thing,2017,122,8.5,William Friedkin,Sigourney Weaver,787806,298791505.0,97.0
Mystery,Vertigo,2012,138,8.4,Terry Gilliam,Vidya Balan,1129894,474203697.0,100.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,165,8.8,Sergio Leone,Henry Fonda,688390,31800000.0,90.0

### Find the top 3 genre by total earning

In [10]:
grouped_genre_data = imdb_data.groupby(by='Genre')

In [11]:
grouped_genre_data.sum()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0
Biography,Schindler's ListGoodfellasHamiltonThe Intoucha...,1993199020202011200220171995198420182013201320...,11970,698.6,Steven SpielbergMartin ScorseseThomas KailOliv...,Liam NeesonRobert De NiroLin-Manuel MirandaÉri...,24006844,8.276358e+09,6023.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0
Crime,The GodfatherThe Godfather: Part II12 Angry Me...,1972197419571994200219991995199120192006199519...,13524,857.8,Francis Ford CoppolaFrancis Ford CoppolaSidney...,Marlon BrandoAl PacinoHenry FondaJohn Travolta...,33533615,8.452632e+09,6706.0
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Family,E.T. the Extra-TerrestrialWilly Wonka & the Ch...,19821971,215,15.6,Steven SpielbergMel Stuart,Henry ThomasGene Wilder,551221,4.391106e+08,158.0
Fantasy,Das Cabinet des Dr. CaligariNosferatu,19201922,170,16.0,Robert WieneF.W. Murnau,Werner KraussMax Schreck,146222,7.827267e+08,0.0
Film-Noir,The Third ManThe Maltese FalconShadow of a Doubt,194919411943,312,23.9,Carol ReedJohn HustonAlfred Hitchcock,Orson WellesHumphrey BogartTeresa Wright,367215,1.259105e+08,287.0
Horror,PsychoAlienThe ThingThe ExorcistNight of the L...,19601979198219731968196120171978193320042001,1123,87.0,Alfred HitchcockRidley ScottJohn CarpenterWill...,Anthony PerkinsSigourney WeaverKurt RussellEll...,3742556,1.034649e+09,880.0
Mystery,MementoRear WindowVertigoShutter IslandKahaani...,200019541958201020121995197219381988201219981997,1429,95.7,Christopher NolanAlfred HitchcockAlfred Hitchc...,Guy PearceJames StewartJames StewartLeonardo D...,4203004,1.256417e+09,633.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,1.755074e+07,81.0
Western,"Il buono, il brutto, il cattivoOnce Upon a Tim...",1966196819651976,593,33.4,Sergio LeoneSergio LeoneSergio LeoneClint East...,Clint EastwoodHenry FondaClint EastwoodClint E...,1289665,5.822151e+07,313.0

In [12]:
grouped_genre_data.sum().sort_values(by='Gross',ascending=False)

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0
Animation,Sen to Chihiro no kamikakushiThe Lion KingHota...,2001199419882016201820172008199719952019200920...,8166,650.3,Hayao MiyazakiRoger AllersIsao TakahataMakoto ...,Daveigh ChaseRob MinkoffTsutomu TatsumiRyûnosu...,21978630,1.463147e+10,6082.0
Adventure,InterstellarBack to the FutureInglourious Bast...,2014198520091981196819621959201319751963194819...,9656,571.5,Christopher NolanRobert ZemeckisQuentin Tarant...,Matthew McConaugheyMichael J. FoxBrad PittJürg...,22576163,9.496922e+09,5020.0
Crime,The GodfatherThe Godfather: Part II12 Angry Me...,1972197419571994200219991995199120192006199519...,13524,857.8,Francis Ford CoppolaFrancis Ford CoppolaSidney...,Marlon BrandoAl PacinoHenry FondaJohn Travolta...,33533615,8.452632e+09,6706.0
Biography,Schindler's ListGoodfellasHamiltonThe Intoucha...,1993199020202011200220171995198420182013201320...,11970,698.6,Steven SpielbergMartin ScorseseThomas KailOliv...,Liam NeesonRobert De NiroLin-Manuel MirandaÉri...,24006844,8.276358e+09,6023.0
Mystery,MementoRear WindowVertigoShutter IslandKahaani...,200019541958201020121995197219381988201219981997,1429,95.7,Christopher NolanAlfred HitchcockAlfred Hitchc...,Guy PearceJames StewartJames StewartLeonardo D...,4203004,1.256417e+09,633.0
Horror,PsychoAlienThe ThingThe ExorcistNight of the L...,19601979198219731968196120171978193320042001,1123,87.0,Alfred HitchcockRidley ScottJohn CarpenterWill...,Anthony PerkinsSigourney WeaverKurt RussellEll...,3742556,1.034649e+09,880.0
Fantasy,Das Cabinet des Dr. CaligariNosferatu,19201922,170,16.0,Robert WieneF.W. Murnau,Werner KraussMax Schreck,146222,7.827267e+08,0.0
Family,E.T. the Extra-TerrestrialWilly Wonka & the Ch...,19821971,215,15.6,Steven SpielbergMel Stuart,Henry ThomasGene Wilder,551221,4.391106e+08,158.0
Film-Noir,The Third ManThe Maltese FalconShadow of a Doubt,194919411943,312,23.9,Carol ReedJohn HustonAlfred Hitchcock,Orson WellesHumphrey BogartTeresa Wright,367215,1.259105e+08,287.0
Western,"Il buono, il brutto, il cattivoOnce Upon a Tim...",1966196819651976,593,33.4,Sergio LeoneSergio LeoneSergio LeoneClint East...,Clint EastwoodHenry FondaClint EastwoodClint E...,1289665,5.822151e+07,313.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,1.755074e+07,81.0

In [13]:
grouped_genre_data.sum().sort_values(by='Gross',ascending=False).head(3)

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Drama,The Shawshank RedemptionFight ClubForrest Gump...,1994199919941975202019981946201420061998198819...,36049,2299.7,Frank DarabontDavid FincherRobert ZemeckisMilo...,Tim RobbinsBrad PittTom HanksJack NicholsonSur...,61367304,3.540997e+10,19208.0
Action,The Dark KnightThe Lord of the Rings: The Retu...,2008200320102001200219991980197719621954200019...,22196,1367.3,Christopher NolanPeter JacksonChristopher Nola...,Christian BaleElijah WoodLeonardo DiCaprioElij...,72282412,3.263226e+10,10499.0
Comedy,GisaengchungLa vita è bellaModern TimesCity Li...,2019199719361931200919641940200120001973196019...,17380,1224.7,Bong Joon HoRoberto BenigniCharles ChaplinChar...,Kang-ho SongRoberto BenigniCharles ChaplinChar...,27620327,1.566387e+10,9840.0

In [14]:
#top 3 earning Genre

grouped_genre_data.sum().sort_values(by='Gross',ascending=False).head(3).index

Index(['Drama', 'Action', 'Comedy'], dtype='object', name='Genre')

### Find the genre with highest average Imdb-rating

In [15]:
grouped_genre_data = imdb_data.groupby(by='Genre')

In [16]:
grouped_genre_data['IMDB_Rating']

In [17]:
grouped_genre_data['IMDB_Rating'].mean()

Genre
Action       7.949419
Adventure    7.937500
Animation    7.930488
Biography    7.938636
Comedy       7.901290
Crime        8.016822
Drama        7.957439
Family       7.800000
Fantasy      8.000000
Film-Noir    7.966667
Horror       7.909091
Mystery      7.975000
Thriller     7.800000
Western      8.350000
Name: IMDB_Rating, dtype: float64

In [18]:
grouped_genre_data['IMDB_Rating'].mean().sort_values(ascending=False)

Genre
Western      8.350000
Crime        8.016822
Fantasy      8.000000
Mystery      7.975000
Film-Noir    7.966667
Drama        7.957439
Action       7.949419
Biography    7.938636
Adventure    7.937500
Animation    7.930488
Horror       7.909091
Comedy       7.901290
Family       7.800000
Thriller     7.800000
Name: IMDB_Rating, dtype: float64

In [19]:
grouped_genre_data['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [20]:
grouped_genre_data['IMDB_Rating'].mean().sort_values(ascending=False).head(1).index # index value of the Genre

Index(['Western'], dtype='object', name='Genre')

### Find Director with most popularity

In [21]:
# consider the vote count for popularity

grouped_data = imdb_data.groupby(by='Director')

In [22]:
grouped_data['No_of_Votes']

In [23]:
grouped_data['No_of_Votes'].sum()

Director
Aamir Khan              168895
Aaron Sorkin             89896
Abdellatif Kechiche     138741
Abhishek Chaubey         27175
Abhishek Kapoor          32628
                        ...
Zack Snyder            1233675
Zaza Urushadze           40382
Zoya Akhtar              99813
Çagan Irmak              78925
Ömer Faruk Sorak         56960
Name: No_of_Votes, Length: 548, dtype: int64

In [24]:
grouped_data['No_of_Votes'].sum().sort_values(ascending=False)

Director
Christopher Nolan    11578345
Quentin Tarantino     8123208
Steven Spielberg      7817166
David Fincher         6607859
Martin Scorsese       6513530
                       ...
J. Lee Thompson         26457
Peter Mullan            25938
René Laloux             25229
Francis Lee             25198
Kaige Chen              25088
Name: No_of_Votes, Length: 548, dtype: int64

In [25]:
grouped_data['No_of_Votes'].sum().sort_values(ascending=False).head(1)

Director
Christopher Nolan    11578345
Name: No_of_Votes, dtype: int64

In [26]:
# Most Popular Director

grouped_data['No_of_Votes'].sum().sort_values(ascending=False).head(1).index

Index(['Christopher Nolan'], dtype='object', name='Director')

### Find number of movies done by each actor

In [27]:
imdb_data.sample(10)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
525,My Left Foot: The Story of Christy Brown,1989,103,Biography,7.9,Jim Sheridan,Daniel Day-Lewis,68076,14743391.0,97.0
972,Delicatessen,1991,99,Comedy,7.6,Marc Caro,Jean-Pierre Jeunet,80487,1794187.0,66.0
663,The Fugitive,1993,130,Action,7.8,Andrew Davis,Harrison Ford,267684,183875760.0,87.0
685,Ghostbusters,1984,105,Action,7.8,Ivan Reitman,Bill Murray,355413,238632124.0,71.0
457,The Grapes of Wrath,1940,129,Drama,8.0,John Ford,Henry Fonda,85559,55000.0,96.0
824,A Few Good Men,1992,138,Drama,7.7,Rob Reiner,Tom Cruise,235388,141340178.0,62.0
268,Platoon,1986,120,Drama,8.1,Oliver Stone,Charlie Sheen,381222,138530565.0,92.0
417,Young Frankenstein,1974,106,Comedy,8.0,Mel Brooks,Gene Wilder,143359,86300000.0,80.0
118,North by Northwest,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
864,Peeping Tom,1960,101,Drama,7.7,Michael Powell,Karlheinz Böhm,31354,83957.0,NaN

In [28]:
imdb_data['Star1'].value_counts().head(1) #use of value-count

Star1
Tom Hanks    12
Name: count, dtype: int64

In [29]:
grouped_data = imdb_data.groupby(by='Star1')

In [30]:
grouped_data['Genre'].count()

Star1
Aamir Khan              7
Aaron Taylor-Johnson    1
Abhay Deol              1
Abraham Attah           1
Adam Driver             1
                       ..
Zbigniew Zamachowski    1
Zooey Deschanel         1
Çetin Tekindor          1
Éric Toledano           1
Ömer Faruk Sorak        1
Name: Genre, Length: 660, dtype: int64

In [31]:
grouped_data['Genre'].count().sort_values(ascending=False)

Star1
Tom Hanks             12
Robert De Niro        11
Clint Eastwood        10
Al Pacino             10
Leonardo DiCaprio      9
                      ..
Glen Hansard           1
Giuseppe Battiston     1
Giulietta Masina       1
Gerardo Taracena       1
Ömer Faruk Sorak       1
Name: Genre, Length: 660, dtype: int64

In [32]:
grouped_data['Genre'].count().sort_values(ascending=False).head(1)

Star1
Tom Hanks    12
Name: Genre, dtype: int64

In [33]:
grouped_data['Genre'].count().sort_values(ascending=False).head(1).index

Index(['Tom Hanks'], dtype='object', name='Star1')

### If we wants to know the no. of groups formed

In [34]:
imdb_data.groupby(by='Genre')

In [35]:
len(imdb_data.groupby(by='Genre')) #1

14

In [36]:
imdb_data['Genre'].nunique() #2

14

### If we wants to know, how many rows are present in the group

In [37]:
imdb_data.groupby(by='Genre').size() #1 Built-in function for group-by, sorted by index

Genre
Action       172
Adventure     72
Animation     82
Biography     88
Comedy       155
Crime        107
Drama        289
Family         2
Fantasy        2
Film-Noir      3
Horror        11
Mystery       12
Thriller       1
Western        4
dtype: int64

In [38]:
imdb_data['Genre'].value_counts() #2 sorted by value count

Genre
Drama        289
Action       172
Comedy       155
Crime        107
Biography     88
Animation     82
Adventure     72
Mystery       12
Horror        11
Western        4
Film-Noir      3
Fantasy        2
Family         2
Thriller       1
Name: count, dtype: int64

### .groupby().first() 

It is used to return the **first non-null value** of each column within each group.

- **Syntax**

        df.groupby(by).first()

| Parameter | Description                          | Default | Possible Values |
|-----------|--------------------------------------|---------|-----------------|
| by        | Column(s) to group by                | —       | label, list     |

---

#### Key Points

- Returns the **first non-NaN row** in each group  
- Works column-wise (skips missing values)  
- Commonly used after sorting to get **top record per group**

In [39]:
grouped_data = imdb_data.groupby(by='Genre')

In [40]:
grouped_data.first() #gives the first non-zero data of each grouped feature

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

### .groupby().last() 

It is used to return the **last non-null value** of each column within each group.

- **Syntax**

        df.groupby(by).last()

| Parameter | Description                          | Default | Possible Values |
|-----------|--------------------------------------|---------|-----------------|
| by        | Column(s) to group by                | —       | label, list     |

---

#### Key Points

- Returns the **last non-NaN row** in each group  
- Works column-wise (skips missing values)  
- Often used after sorting to get the **latest record per group**

In [41]:
grouped_data.last() # gives the very last row of each group.

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,Escape from Alcatraz,1979,112,7.6,Don Siegel,Clint Eastwood,121731,43000000.0,76.0
Adventure,Kelly's Heroes,1970,144,7.6,Brian G. Hutton,Clint Eastwood,45338,1378435.0,50.0
Animation,The Jungle Book,1967,78,7.6,Wolfgang Reitherman,Phil Harris,166409,141843612.0,65.0
Biography,Midnight Express,1978,121,7.6,Alan Parker,Brad Davis,73662,35000000.0,59.0
Comedy,Breakfast at Tiffany's,1961,115,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
Crime,The 39 Steps,1935,86,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0
Drama,Lifeboat,1944,97,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
Family,Willy Wonka & the Chocolate Factory,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Nosferatu,1922,94,7.9,F.W. Murnau,Max Schreck,88794,445151978.0,NaN
Film-Noir,Shadow of a Doubt,1943,108,7.8,Alfred Hitchcock,Teresa Wright,59556,123353292.0,94.0
Horror,The Others,2001,101,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0
Mystery,Lost Highway,1997,134,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,The Outlaw Josey Wales,1976,135,7.8,Clint Eastwood,Clint Eastwood,65659,31800000.0,69.0

### .groupby().nth() 

It is used to return the **nth row** from each group.

- **Syntax**

        df.groupby(by).nth(n)

| Parameter | Description                          | Default | Possible Values            |
|-----------|--------------------------------------|---------|----------------------------|
| by        | Column(s) to group by                | —       | label, list                |
| n         | Position of row to select            | —       | int, list of ints          |
| dropna    | Exclude NaN values before selection  | None    | 'any', 'all', None         |

---

#### Key Points

- Returns row(s) at a specific position from each group  
- Unlike `.first()` / `.last()`, it **does not skip NaN by default**  
- Can select multiple positions using a list

In [42]:
grouped_data.nth(6) #extract 7th row of each group formed

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
16,Star Wars: Episode V - The Empire Strikes Back,1980,124,Action,8.7,Irvin Kershner,Mark Hamill,1159315,290475067.0,82.0
27,Se7en,1995,127,Crime,8.6,David Fincher,Morgan Freeman,1445096,100125643.0,65.0
32,It's a Wonderful Life,1946,130,Drama,8.6,Frank Capra,James Stewart,405801,82385199.0,89.0
66,WALL·E,2008,98,Animation,8.4,Andrew Stanton,Ben Burtt,999790,223808164.0,95.0
83,The Great Dictator,1940,125,Comedy,8.4,Charles Chaplin,Charles Chaplin,203150,288475.0,NaN
102,Braveheart,1995,178,Biography,8.3,Mel Gibson,Mel Gibson,959181,75600000.0,68.0
118,North by Northwest,1959,136,Adventure,8.3,Alfred Hitchcock,Cary Grant,299198,13275000.0,98.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0

In [43]:
grouped_data.nth([4,8,9]) # extract 5th, 9th and 10th row of each group formed

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
13,The Lord of the Rings: The Two Towers,2002,179,Action,8.7,Peter Jackson,Elijah Wood,1485555,342551365.0,87.0
20,Soorarai Pottru,2020,153,Drama,8.6,Sudha Kongara,Suriya,54995,556832648.0,NaN
22,Cidade de Deus,2002,130,Crime,8.6,Fernando Meirelles,Kátia Lund,699256,7563397.0,79.0
30,Seppuku,1962,133,Action,8.6,Masaki Kobayashi,Tatsuya Nakadai,42004,373978394.0,85.0
31,Shichinin no samurai,1954,207,Action,8.6,Akira Kurosawa,Toshirô Mifune,315744,269061.0,98.0
33,Joker,2019,122,Crime,8.5,Todd Phillips,Joaquin Phoenix,939252,335451311.0,59.0
36,The Prestige,2006,130,Drama,8.5,Christopher Nolan,Christian Bale,1190259,53089891.0,66.0
37,The Departed,2006,151,Crime,8.5,Martin Scorsese,Leonardo DiCaprio,1189773,132384315.0,85.0
38,The Pianist,2002,150,Biography,8.5,Roman Polanski,Adrien Brody,729603,32572577.0,85.0
40,American History X,1998,119,Drama,8.5,Tony Kaye,Edward Norton,1034705,6719864.0,62.0
58,Spider-Man: Into the Spider-Verse,2018,117,Animation,8.4,Bob Persichetti,Peter Ramsey,375110,190241310.0,87.0
64,3 Idiots,2009,170,Comedy,8.4,Rajkumar Hirani,Aamir Khan,344445,6532908.0,67.0
96,Snatch,2000,104,Comedy,8.3,Guy Ritchie,Jason Statham,782001,30328156.0,55.0
101,Toy Story,1995,81,Animation,8.3,John Lasseter,Tom Hanks,887429,191796233.0,95.0
112,The Sting,1973,129,Comedy,8.3,George Roy Hill,Paul Newman,241513,159600000.0,83.0
114,2001: A Space Odyssey,1968,149,Adventure,8.3,Stanley Kubrick,Keir Dullea,603517,56954992.0,84.0
131,Green Book,2018,130,Biography,8.2,Peter Farrelly,Viggo Mortensen,377884,85080171.0,69.0
135,Klaus,2019,96,Animation,8.2,Sergio Pablos,Carlos Martínez López,104761,148596026.0,65.0
139,Bhaag Milkha Bhaag,2013,186,Biography,8.2,Rakeysh Omprakash Mehra,Farhan Akhtar,61137,1626289.0,NaN
178,Monty Python and the Holy Grail,1975,91,Adventure,8.2,Terry Gilliam,Terry Jones,500875,1229197.0,91.0
179,The Great Escape,1963,172,Adventure,8.2,John Sturges,Steve McQueen,224730,12100000.0,86.0
220,Kahaani,2012,122,Mystery,8.1,Sujoy Ghosh,Vidya Balan,57806,1035953.0,NaN
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
829,Spoorloos,1988,107,Mystery,7.7,George Sluizer,Bernard-Pierre Donnadieu,33982,367916835.0,NaN
876,The Invisible Man,1933,71,Horror,7.7,James Whale,Claude Rains,30683,298791505.0,87.0
899,El cuerpo,2012,112,Mystery,7.6,Oriol Paulo,Jose Coronado,57549,140340673.0,NaN
932,Saw,2004,103,Horror,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0

### .groupby().get_group() 

It is used to retrieve a specific group from a GroupBy object.

- **Syntax**

        df.groupby(by).get_group(name)

| Parameter | Description                          | Default | Possible Values |
|-----------|--------------------------------------|---------|-----------------|
| by        | Column(s) to group by                | —       | label, list     |
| name      | Group key to retrieve                | —       | value, tuple    |

---

#### Key Points

- Returns all rows corresponding to a specific group  
- Useful for inspecting or operating on a single group  
- `name` should match one of the group keys

In [44]:
grouped_data.get_group('Mystery') #get all data which is present in Mystery group

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
69,Memento,2000,113,Mystery,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
81,Rear Window,1954,112,Mystery,8.4,Alfred Hitchcock,James Stewart,444074,36764313.0,100.0
119,Vertigo,1958,128,Mystery,8.3,Alfred Hitchcock,James Stewart,364368,3200000.0,100.0
145,Shutter Island,2010,138,Mystery,8.2,Martin Scorsese,Leonardo DiCaprio,1129894,128012934.0,63.0
220,Kahaani,2012,122,Mystery,8.1,Sujoy Ghosh,Vidya Balan,57806,1035953.0,NaN
393,Twelve Monkeys,1995,129,Mystery,8.0,Terry Gilliam,Bruce Willis,578443,57141459.0,74.0
420,Sleuth,1972,138,Mystery,8.0,Joseph L. Mankiewicz,Laurence Olivier,44748,4081254.0,NaN
714,The Lady Vanishes,1938,96,Mystery,7.8,Alfred Hitchcock,Margaret Lockwood,47400,474203697.0,98.0
829,Spoorloos,1988,107,Mystery,7.7,George Sluizer,Bernard-Pierre Donnadieu,33982,367916835.0,NaN
899,El cuerpo,2012,112,Mystery,7.6,Oriol Paulo,Jose Coronado,57549,140340673.0,NaN
959,Dark City,1998,100,Mystery,7.6,Alex Proyas,Rufus Sewell,187927,14378331.0,66.0
961,Lost Highway,1997,134,Mystery,7.6,David Lynch,Bill Pullman,131101,3796699.0,52.0

### .groupby().groups 

It is used to get a dictionary of group names and their corresponding index labels.

- **Syntax**

        df.groupby(by).groups

| Parameter | Description                          | Default | Possible Values |
|-----------|--------------------------------------|---------|-----------------|
| by        | Column(s) to group by                | —       | label, list     |

---

#### Key Points

- Returns a **dictionary** where:
  - keys → group names  
  - values → index labels belonging to each group  
- Useful for understanding how data is split into groups

In [45]:
grouped_data.groups

{'Action': [2, 5, 8, 10, 13, 14, 16, 29, 30, 31, 39, 42, 44, 55, 57, 59, 60, 63, 68, 72, 106, 109, 129, 130, 134, 140, 142, 144, 152, 155, 160, 161, 166, 168, 171, 172, 177, 181, 194, 201, 202, 216, 217, 223, 224, 236, 241, 262, 275, 294, 308, 320, 325, 326, 331, 337, 339, 340, 343, 345, 348, 351, 353, 356, 357, 362, 368, 369, 375, 376, 390, 410, 431, 436, 473, 477, 479, 482, 488, 493, 496, 502, 507, 511, 532, 535, 540, 543, 564, 569, 570, 573, 577, 582, 583, 602, 605, 608, 615, 623, ...], 'Adventure': [21, 47, 93, 110, 114, 116, 118, 137, 178, 179, 191, 193, 209, 226, 231, 247, 267, 273, 281, 300, 301, 304, 306, 323, 329, 361, 366, 377, 402, 406, 415, 426, 458, 470, 497, 498, 506, 513, 514, 537, 549, 552, 553, 566, 576, 604, 609, 618, 638, 647, 675, 681, 686, 692, 711, 713, 739, 755, 781, 797, 798, 851, 873, 884, 912, 919, 947, 957, 964, 966, 984, 991], 'Animation': [23, 43, 46, 56, 58, 61, 66, 70, 101, 135, 146, 151, 158, 170, 197, 205, 211, 213, 219, 229, 230, 242, 245, 246, 270, 330, 332, 358, 367, 378, 386, 389, 394, 395, 399, 401, 405, 409, 469, 499, 510, 516, 518, 522, 578, 586, 592, 595, 596, 599, 633, 640, 643, 651, 665, 672, 694, 728, 740, 741, 744, 756, 758, 761, 771, 783, 796, 799, 822, 828, 843, 875, 891, 892, 902, 906, 920, 956, 971, 976, 986, 992], 'Biography': [7, 15, 18, 35, 38, 54, 102, 107, 131, 139, 147, 157, 159, 173, 176, 212, 215, 218, 228, 235, 243, 263, 276, 282, 290, 298, 317, 328, 338, 342, 346, 359, 360, 365, 372, 373, 385, 411, 416, 418, 424, 429, 484, 525, 536, 542, 545, 575, 579, 587, 600, 606, 614, 622, 632, 635, 644, 649, 650, 657, 671, 673, 684, 729, 748, 753, 757, 759, 766, 770, 779, 809, 810, 815, 820, 831, 849, 858, 877, 882, 897, 910, 915, 923, 940, 949, 952, 987], 'Comedy': [19, 26, 51, 52, 64, 78, 83, 95, 96, 112, 117, 120, 127, 128, 132, 153, 169, 183, 192, 204, 207, 208, 214, 221, 233, 238, 240, 250, 251, 252, 256, 261, 266, 277, 284, 311, 313, 316, 318, 322, 327, 374, 379, 381, 392, 396, 403, 413, 414, 417, 427, 435, 445, 446, 449, 455, 459, 460, 463, 464, 466, 471, 472, 475, 481, 490, 494, 500, 503, 509, 526, 528, 530, 531, 533, 538, 539, 541, 547, 557, 558, 562, 563, 565, 574, 591, 593, 594, 598, 613, 626, 630, 660, 662, 667, 679, 680, 683, 687, 701, ...], 'Crime': [1, 3, 4, 6, 22, 25, 27, 28, 33, 37, 41, 71, 77, 79, 86, 87, 103, 108, 111, 113, 123, 125, 133, 136, 162, 163, 164, 165, 180, 186, 187, 189, 198, 222, 232, 239, 255, 257, 287, 288, 299, 305, 335, 363, 364, 380, 384, 397, 437, 438, 441, 442, 444, 450, 451, 465, 474, 480, 485, 487, 505, 512, 519, 520, 523, 527, 546, 556, 560, 584, 597, 603, 607, 611, 621, 639, 653, 664, 669, 676, 695, 708, 723, 762, 763, 767, 775, 791, 795, 802, 811, 823, 827, 833, 885, 895, 921, 922, 926, 938, ...], 'Drama': [0, 9, 11, 17, 20, 24, 32, 34, 36, 40, 45, 50, 53, 62, 65, 67, 73, 74, 76, 80, 82, 84, 85, 88, 89, 90, 91, 92, 94, 97, 98, 99, 100, 104, 105, 121, 122, 124, 126, 138, 141, 143, 148, 149, 150, 154, 156, 167, 174, 175, 182, 184, 185, 188, 190, 195, 196, 199, 200, 203, 206, 210, 225, 227, 234, 237, 244, 248, 249, 253, 254, 258, 259, 260, 264, 265, 268, 269, 272, 274, 278, 279, 280, 283, 285, 286, 289, 291, 292, 293, 295, 296, 297, 302, 303, 307, 310, 312, 314, 315, ...], 'Family': [688, 698], 'Fantasy': [321, 568], 'Film-Noir': [309, 456, 712], 'Horror': [49, 75, 271, 419, 544, 707, 724, 844, 876, 932, 948], 'Mystery': [69, 81, 119, 145, 220, 393, 420, 714, 829, 899, 959, 961], 'Thriller': [700], 'Western': [12, 48, 115, 691]}

### .groupby().describe() 

It is used to generate **descriptive statistics** for each group in the data.

- **Syntax**

        df.groupby(by).describe()

| Parameter | Description                          | Default | Possible Values |
|-----------|--------------------------------------|---------|-----------------|
| by        | Column(s) to group by                | —       | label, list     |

---

#### Key Points

- Provides summary statistics like:
  - count, mean, std, min, 25%, 50%, 75%, max  
- Output is a **multi-level column DataFrame**  
- Useful for quick exploratory data analysis (EDA)

In [46]:
grouped_data.describe() #perform describe function on each feature, group wise

          Runtime                                                              \
            count        mean        std    min     25%    50%     75%    max
Genre
Action      172.0  129.046512  28.500706   45.0  110.75  127.5  143.25  321.0
Adventure    72.0  134.111111  33.317320   88.0  109.00  127.0  149.00  228.0
Animation    82.0   99.585366  14.530471   71.0   90.00   99.5  106.75  137.0
Biography    88.0  136.022727  25.514466   93.0  120.00  129.0  146.25  209.0
Comedy      155.0  112.129032  22.946213   68.0   96.00  106.0  124.50  188.0
Crime       107.0  126.392523  27.689231   80.0  106.50  122.0  141.50  229.0
Drama       289.0  124.737024  27.740490   64.0  105.00  121.0  137.00  242.0
Family        2.0  107.500000  10.606602  100.0  103.75  107.5  111.25  115.0
Fantasy       2.0   85.000000  12.727922   76.0   80.50   85.0   89.50   94.0
Film-Noir     3.0  104.000000   4.000000  100.0  102.00  104.0  106.00  108.0
Horror       11.0  102.090909  13.604812   71.0   98.00  103.0  109.00  122.0
Mystery      12.0  119.083333  14.475423   96.0  110.75  117.5  130.25  138.0
Thriller      1.0  108.000000        NaN  108.0  108.00  108.0  108.00  108.0
Western       4.0  148.250000  17.153717  132.0  134.25  148.0  162.00  165.0

          IMDB_Rating            ...         Gross              Metascore  \
                count      mean  ...           75%          max     count
Genre                            ...
Action          172.0  7.949419  ...  2.674437e+08  936662225.0     143.0
Adventure        72.0  7.937500  ...  1.998070e+08  874211619.0      64.0
Animation        82.0  7.930488  ...  2.520612e+08  873839108.0      75.0
Biography        88.0  7.938636  ...  9.829924e+07  753585104.0      79.0
Comedy          155.0  7.901290  ...  8.107809e+07  886752933.0     125.0
Crime           107.0  8.016822  ...  7.102163e+07  790482117.0      87.0
Drama           289.0  7.957439  ...  1.164461e+08  924558264.0     241.0
Family            2.0  7.800000  ...  3.273329e+08  435110554.0       2.0
Fantasy           2.0  8.000000  ...  4.182577e+08  445151978.0       0.0
Film-Noir         3.0  7.966667  ...  6.273068e+07  123353292.0       3.0
Horror           11.0  7.909091  ...  1.362817e+08  298791505.0      11.0
Mystery          12.0  7.975000  ...  1.310949e+08  474203697.0       8.0
Thriller          1.0  7.800000  ...  1.755074e+07   17550741.0       1.0
Western           4.0  8.350000  ...  1.920000e+07   31800000.0       4.0


                mean        std   min    25%   50%    75%    max
Genre
Action     73.419580  12.421252  33.0  65.00  74.0  82.00   98.0
Adventure  78.437500  12.345393  41.0  69.75  80.5  87.25  100.0
Animation  81.093333   8.813646  61.0  75.00  82.0  87.50   96.0
Biography  76.240506  11.028187  48.0  70.50  76.0  84.50   97.0
Comedy     78.720000  11.829160  45.0  72.00  79.0  88.00   99.0
Crime      77.080460  13.099102  47.0  69.50  77.0  87.00  100.0
Drama      79.701245  12.744687  28.0  72.00  82.0  89.00  100.0
Family     79.000000  16.970563  67.0  73.00  79.0  85.00   91.0
Fantasy          NaN        NaN   NaN    NaN   NaN    NaN    NaN
Film-Noir  95.666667   1.527525  94.0  95.00  96.0  96.50   97.0
Horror     80.000000  15.362291  46.0  77.50  87.0  88.50   97.0
Mystery    79.125000  18.604435  52.0  65.25  77.0  98.50  100.0
Thriller   81.000000        NaN  81.0  81.00  81.0  81.00   81.0
Western    78.250000   9.032349  69.0  72.75  77.0  82.50   90.0

[14 rows x 40 columns]

### .groupby().sample() 

It is used to randomly sample rows from each group.

- **Syntax**

        df.groupby(by).sample(n=None, frac=None)

| Parameter    | Description                                              | Default | Possible Values                          |
|--------------|----------------------------------------------------------|---------|------------------------------------------|
| by           | Column(s) to group by                                    | —       | label, list                              |
| n            | Number of items to return per group                      | None    | int                                      |
| frac         | Fraction of items to return per group                    | None    | float (0–1)                              |
| replace      | Allow sampling with replacement                          | False   | True, False                              |
| random_state | Seed for reproducibility                                 | None    | int                                      |

---

#### Key Points

- Performs **random sampling within each group**  
- Use `n` for fixed number or `frac` for percentage  
- Helps in **balanced sampling** from grouped data

In [47]:
grouped_data.sample() #get a random data from each group

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
968,Falling Down,1993,113,Action,7.6,Joel Schumacher,Michael Douglas,171640,40903593.0,56.0
497,The Fall,2006,117,Adventure,7.9,Tarsem Singh,Lee Pace,107290,2280348.0,64.0
761,Toki o kakeru shôjo,2006,98,Animation,7.7,Mamoru Hosoda,Riisa Naka,60368,329525432.0,NaN
212,Hacksaw Ridge,2016,139,Biography,8.1,Mel Gibson,Andrew Garfield,435928,67209615.0,71.0
733,Birdman or (The Unexpected Virtue of Ignorance),2014,119,Comedy,7.7,Alejandro G. Iñárritu,Michael Keaton,580291,42340598.0,87.0
25,The Green Mile,1999,189,Crime,8.6,Frank Darabont,Tom Hanks,1147794,136801374.0,61.0
818,Philadelphia,1993,125,Drama,7.7,Jonathan Demme,Tom Hanks,224169,77324422.0,66.0
698,Willy Wonka & the Chocolate Factory,1971,100,Family,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
321,Das Cabinet des Dr. Caligari,1920,76,Fantasy,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
456,The Maltese Falcon,1941,100,Film-Noir,8.0,John Huston,Humphrey Bogart,148928,2108060.0,96.0
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
899,El cuerpo,2012,112,Mystery,7.6,Oriol Paulo,Jose Coronado,57549,140340673.0,NaN
700,Wait Until Dark,1967,108,Thriller,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
48,Once Upon a Time in the West,1968,165,Western,8.5,Sergio Leone,Henry Fonda,302844,5321508.0,80.0

### .groupby().nunique() 

It is used to count the number of **unique values** in each group.

- **Syntax**

        df.groupby(by).nunique(dropna=True)

| Parameter | Description                                   | Default | Possible Values |
|-----------|-----------------------------------------------|---------|-----------------|
| by        | Column(s) to group by                         | —       | label, list     |
| dropna    | Exclude NaN values from the count             | True    | True, False     |

---

#### Key Points

- Counts distinct values **within each group**  
- Works column-wise for DataFrames  
- Useful for identifying **diversity or uniqueness in groups**

In [48]:
grouped_data.nunique()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,172,61,78,15,123,121,172,172,50
Adventure,72,49,58,10,59,59,72,72,33
Animation,82,35,41,11,51,77,82,82,29
Biography,88,44,56,13,76,72,88,88,40
Comedy,155,72,70,11,113,133,155,155,44
Crime,106,56,65,14,86,85,107,107,39
Drama,289,83,95,14,211,250,288,287,52
Family,2,2,2,1,2,2,2,2,2
Fantasy,2,2,2,2,2,2,2,2,0
Film-Noir,3,3,3,3,3,3,3,3,3
Horror,11,11,10,8,10,11,11,11,9
Mystery,12,11,10,8,10,11,12,12,7
Thriller,1,1,1,1,1,1,1,1,1
Western,4,4,4,4,2,2,4,4,4

### .groupby().agg() 

It is used to apply one or multiple **aggregate functions** to grouped data.

- **Syntax**

        df.groupby(by).agg(func)

| Parameter | Description                                              | Default | Possible Values                          |
|-----------|----------------------------------------------------------|---------|------------------------------------------|
| by        | Column(s) to group by                                    | —       | label, list                              |
| func      | Function(s) to apply                                     | —       | function, string, list, dict             |
| axis      | Axis along which aggregation is performed                | 0       | 0 (rows), 1 (columns)                    |

---

#### Key Points

- Can apply **single or multiple aggregations**  
- Supports:
  - list of functions → `['mean', 'sum']`  
  - dictionary mapping → `{'col1': 'mean', 'col2': 'sum'}`  
- Returns aggregated result per group

In [49]:
grouped_data.agg([min, max]) # getting min & max for each column

/var/folders/94/2_5s7zqj0cqd50nz6b9khlxh0000gp/T/ipykernel_21350/2987781554.py:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  grouped_data.agg([min, max]) # getting min & max for each column
/var/folders/94/2_5s7zqj0cqd50nz6b9khlxh0000gp/T/ipykernel_21350/2987781554.py:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  grouped_data.agg([min, max]) # getting min & max for each column

                              Series_Title  \
                                       min
Genre
Action                                 300
Adventure            2001: A Space Odyssey
Animation                            Akira
Biography                 12 Years a Slave
Comedy                (500) Days of Summer
Crime                         12 Angry Men
Drama                                 1917
Family          E.T. the Extra-Terrestrial
Fantasy       Das Cabinet des Dr. Caligari
Film-Noir                Shadow of a Doubt
Horror                               Alien
Mystery                          Dark City
Thriller                   Wait Until Dark
Western    Il buono, il brutto, il cattivo

                                               Released_Year       Runtime  \
                                           max           min   max     min
Genre
Action                                 Yôjinbô          1924  2019      45
Adventure                           Zombieland          1925    PG      88
Animation          Ôkami kodomo no Ame to Yuki          1940  2020      71
Biography                              Zerkalo          1928  2020      93
Comedy                Zindagi Na Milegi Dobara          1921  2020      68
Crime                        À bout de souffle          1931  2019      80
Drama                                Zwartboek          1925  2020      64
Family     Willy Wonka & the Chocolate Factory          1971  1982     100
Fantasy                              Nosferatu          1920  1922      76
Film-Noir                        The Third Man          1941  1949     100
Horror                               The Thing          1933  2017      71
Mystery                                Vertigo          1938  2012      96
Thriller                       Wait Until Dark          1967  1967     108
Western                 The Outlaw Josey Wales          1965  1976     132

               IMDB_Rating                    Director                    \
           max         min  max                    min               max
Genre
Action     321         7.6  9.0       Abhishek Chaubey       Zack Snyder
Adventure  228         7.6  8.6         Akira Kurosawa  Ömer Faruk Sorak
Animation  137         7.6  8.6            Adam Elliot   Yoshifumi Kondô
Biography  209         7.6  8.9             Adam McKay      Tom McCarthy
Comedy     188         7.6  8.6  Alejandro G. Iñárritu       Zoya Akhtar
Crime      229         7.6  9.2         Akira Kurosawa      Yavuz Turgul
Drama      242         7.6  9.3             Aamir Khan       Çagan Irmak
Family     115         7.8  7.8             Mel Stuart  Steven Spielberg
Fantasy     94         7.9  8.1            F.W. Murnau      Robert Wiene
Film-Noir  108         7.8  8.1       Alfred Hitchcock       John Huston
Horror     122         7.6  8.5     Alejandro Amenábar  William Friedkin
Mystery    138         7.6  8.4            Alex Proyas     Terry Gilliam
Thriller   108         7.8  7.8          Terence Young     Terence Young
Western    165         7.8  8.8         Clint Eastwood      Sergio Leone

                              Star1                   No_of_Votes           \
                                min               max         min      max
Genre
Action                   Aamir Khan      Yun-Fat Chow       25312  2303232
Adventure                Aamir Khan      Yves Montand       29999  1512360
Animation             Adrian Molina      Yôji Matsuda       25229   999790
Biography              Adrien Brody     Éric Toledano       27254  1213505
Comedy                   Aamir Khan  Ömer Faruk Sorak       26337   939631
Crime                    Ajay Devgn    Vincent Cassel       27712  1826188
Drama                    Abhay Deol    Çetin Tekindor       25088  2343110
Family                  Gene Wilder      Henry Thomas      178731   372490
Fantasy                 Max Schreck     Werner Krauss       57428    88794
Film-Noir           Humphrey Bogart     Teresa Wright       59556   158731
Horror              Anthony Perkins  Sigourney Weaver       27007   787806
Mystery    Bernard-Pierre Donnadieu       Vidya Balan       33982  1129894
Thriller             Audrey Hepburn    Audrey Hepburn       27733    27733
Western              Clint Eastwood       Henry Fonda       65659   688390

                 Gross              Metascore
                   min          max       min    max
Genre
Action          3296.0  936662225.0      33.0   98.0
Adventure      61001.0  874211619.0      41.0  100.0
Animation     128985.0  873839108.0      61.0   96.0
Biography      21877.0  753585104.0      48.0   97.0
Comedy          1305.0  886752933.0      45.0   99.0
Crime           6013.0  790482117.0      47.0  100.0
Drama           3600.0  924558264.0      28.0  100.0
Family       4000000.0  435110554.0      67.0   91.0
Fantasy    337574718.0  445151978.0       NaN    NaN
Film-Noir     449191.0  123353292.0      94.0   97.0
Horror         89029.0  298791505.0      46.0   97.0
Mystery      1035953.0  474203697.0      52.0  100.0
Thriller    17550741.0   17550741.0      81.0   81.0
Western      5321508.0   31800000.0      69.0   90.0

In [50]:
#custom aggregate function
grouped_data.agg(
    {
        'Runtime': ['mean','max','min'],
        'IMDB_Rating':['mean','max','min'],
        'Gross':'sum'
    }
)

              Runtime           IMDB_Rating                   Gross
                 mean  max  min        mean  max  min           sum
Genre
Action     129.046512  321   45    7.949419  9.0  7.6  3.263226e+10
Adventure  134.111111  228   88    7.937500  8.6  7.6  9.496922e+09
Animation   99.585366  137   71    7.930488  8.6  7.6  1.463147e+10
Biography  136.022727  209   93    7.938636  8.9  7.6  8.276358e+09
Comedy     112.129032  188   68    7.901290  8.6  7.6  1.566387e+10
Crime      126.392523  229   80    8.016822  9.2  7.6  8.452632e+09
Drama      124.737024  242   64    7.957439  9.3  7.6  3.540997e+10
Family     107.500000  115  100    7.800000  7.8  7.8  4.391106e+08
Fantasy     85.000000   94   76    8.000000  8.1  7.9  7.827267e+08
Film-Noir  104.000000  108  100    7.966667  8.1  7.8  1.259105e+08
Horror     102.090909  122   71    7.909091  8.5  7.6  1.034649e+09
Mystery    119.083333  138   96    7.975000  8.4  7.6  1.256417e+09
Thriller   108.000000  108  108    7.800000  7.8  7.8  1.755074e+07
Western    148.250000  165  132    8.350000  8.8  7.8  5.822151e+07

### Looping in Grouped Data (`.groupby()`)

It is used to iterate over each group in a GroupBy object to perform custom operations.

- **Syntax**

        for name, group in df.groupby(by):
            # operations on group

| Parameter | Description                          | Default | Possible Values |
|-----------|--------------------------------------|---------|-----------------|
| by        | Column(s) to group by                | —       | label, list     |
| name      | Group key (unique value of group)    | —       | varies          |
| group     | Subset of DataFrame for that group   | —       | DataFrame       |

---

#### Key Points

- Iterates over **(group_name, group_data)** pairs  
- `group` is a **DataFrame subset** corresponding to that group  
- Useful for **custom logic not covered by built-in functions**

In [51]:
for group, data in grouped_data:
    print(group)
    print(' ')
    print(data)

Action

                                          Series_Title Released_Year  Runtime  \
2                                      The Dark Knight          2008      152
5        The Lord of the Rings: The Return of the King          2003      201
8                                            Inception          2010      148
10   The Lord of the Rings: The Fellowship of the Ring          2001      178
13               The Lord of the Rings: The Two Towers          2002      179
..                                                 ...           ...      ...
968                                       Falling Down          1993      113
979                                      Lethal Weapon          1987      109
982                                          Mad Max 2          1981       96
983                                       The Warriors          1979       92
985                               Escape from Alcatraz          1979      112

      Genre  IMDB_Rating           Director              Star1  No_of_Votes  \
2    Action          9.0  Christopher Nolan     Christian Bale      2303232
5    Action          8.9      Peter Jackson        Elijah Wood      1642758
8    Action          8.8  Christopher Nolan  Leonardo DiCaprio      2067042
10   Action          8.8      Peter Jackson        Elijah Wood      1661481
13   Action          8.7      Peter Jackson        Elijah Wood      1485555
..      ...          ...                ...                ...          ...
968  Action          7.6    Joel Schumacher    Michael Douglas       171640
979  Action          7.6     Richard Donner         Mel Gibson       236894
982  Action          7.6      George Miller         Mel Gibson       166588
983  Action          7.6        Walter Hill       Michael Beck        93878
985  Action          7.6         Don Siegel     Clint Eastwood       121731

           Gross  Metascore
2    534858444.0       84.0
5    377845905.0       94.0
8    292576195.0       74.0
10   315544750.0       92.0
13   342551365.0       87.0
..           ...        ...
968   40903593.0       56.0
979   65207127.0       68.0
982   12465371.0       77.0
983   22490039.0       65.0
985   43000000.0       76.0

[172 rows x 10 columns]
Adventure

                       Series_Title Released_Year  Runtime      Genre  \
21                     Interstellar          2014      169  Adventure
47               Back to the Future          1985      116  Adventure
93             Inglourious Basterds          2009      153  Adventure
110                        Das Boot          1981      149  Adventure
114           2001: A Space Odyssey          1968      149  Adventure
..                              ...           ...      ...        ...
957  Fear and Loathing in Las Vegas          1998      118  Adventure
964                        Dead Man          1995      121  Adventure
966                       Apollo 13            PG      140  Adventure
984                The Muppet Movie          1979       95  Adventure
991                  Kelly's Heroes          1970      144  Adventure

     IMDB_Rating           Director                Star1  No_of_Votes  \
21           8.6  Christopher Nolan  Matthew McConaughey      1512360
47           8.5    Robert Zemeckis       Michael J. Fox      1058081
93           8.3  Quentin Tarantino            Brad Pitt      1267869
110          8.3  Wolfgang Petersen      Jürgen Prochnow       231855
114          8.3    Stanley Kubrick          Keir Dullea       603517
..           ...                ...                  ...          ...
957          7.6      Terry Gilliam          Johnny Depp       259753
964          7.6       Jim Jarmusch          Johnny Depp        90442
966          7.6         Ron Howard            Tom Hanks       269197
984          7.6      James Frawley           Jim Henson        32802
991          7.6    Brian G. Hutton       Clint Eastwood        45338

           Gross  Metascore
21   188020017.0       74.0
47   210609762.0       87.0
93   120540719.0       69.0
110   11487676.0       86.0
114   56954992.0       84.0
..           ...        ...
957   10680275.0       41.0
964    1037847.0       62.0
966  173837933.0       77.0
984   76657000.0       74.0
991    1378435.0       50.0

[72 rows x 10 columns]
Animation

                          Series_Title Released_Year  Runtime      Genre  \
23       Sen to Chihiro no kamikakushi          2001      125  Animation
43                       The Lion King          1994       88  Animation
46                      Hotaru no haka          1988       89  Animation
56                      Kimi no na wa.          2016      106  Animation
58   Spider-Man: Into the Spider-Verse          2018      117  Animation
..                                 ...           ...      ...        ...
956                              Mulan          1998       88  Animation
971                  Omohide poro poro          1991      118  Animation
976                 The Little Mermaid          1989       83  Animation
986                     Watership Down          1978       91  Animation
992                    The Jungle Book          1967       78  Animation

     IMDB_Rating             Director             Star1  No_of_Votes  \
23           8.6       Hayao Miyazaki     Daveigh Chase       651376
43           8.5         Roger Allers       Rob Minkoff       942045
46           8.5        Isao Takahata   Tsutomu Tatsumi       235231
56           8.4       Makoto Shinkai  Ryûnosuke Kamiki       194838
58           8.4      Bob Persichetti      Peter Ramsey       375110
..           ...                  ...               ...          ...
956          7.6        Tony Bancroft        Barry Cook       256906
971          7.6        Isao Takahata         Miki Imai        27071
976          7.6         Ron Clements       John Musker       237696
986          7.6         Martin Rosen       John Hubley        33656
992          7.6  Wolfgang Reitherman       Phil Harris       166409

           Gross  Metascore
23    10055859.0       96.0
43   422783777.0       88.0
46   150734678.0       94.0
56     5017246.0       79.0
58   190241310.0       87.0
..           ...        ...
956  120620254.0       71.0
971     453243.0       90.0
976  111543479.0       88.0
986  232841485.0       64.0
992  141843612.0       65.0

[82 rows x 10 columns]
Biography

          Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
7     Schindler's List          1993      195  Biography          8.9
15          Goodfellas          1990      146  Biography          8.7
18            Hamilton          2020      160  Biography          8.6
35    The Intouchables          2011      112  Biography          8.5
38         The Pianist          2002      150  Biography          8.5
..                 ...           ...      ...        ...          ...
923     La Vie En Rose          2007      140  Biography          7.6
940  Finding Neverland          2004      106  Biography          7.6
949               Blow          2001      124  Biography          7.6
952      The Hurricane          1999      146  Biography          7.6
987   Midnight Express          1978      121  Biography          7.6

             Director               Star1  No_of_Votes        Gross  Metascore
7    Steven Spielberg         Liam Neeson      1213505   96898818.0       94.0
15    Martin Scorsese      Robert De Niro      1020727   46836394.0       90.0
18        Thomas Kail  Lin-Manuel Miranda        55291  440984783.0       90.0
35    Olivier Nakache       Éric Toledano       760360   13182281.0       57.0
38     Roman Polanski        Adrien Brody       729603   32572577.0       85.0
..                ...                 ...          ...          ...        ...
923     Olivier Dahan    Marion Cotillard        82781   10301706.0       66.0
940      Marc Forster         Johnny Depp       198677   51680613.0       67.0
949         Ted Demme         Johnny Depp       240714   52990775.0       52.0
952    Norman Jewison   Denzel Washington        91557   50668906.0       74.0
987       Alan Parker          Brad Davis        73662   35000000.0       59.0

[88 rows x 10 columns]
Comedy

                                       Series_Title Released_Year  Runtime  \
19                                     Gisaengchung          2019      132
26                                  La vita è bella          1997      116
51                                     Modern Times          1936       87
52                                      City Lights          1931       87
64                                         3 Idiots          2009      170
..                                              ...           ...      ...
977  The Naked Gun: From the Files of Police Squad!          1988       85
978                    Planes, Trains & Automobiles          1987       93
989                                The Long Goodbye          1973      112
994                              A Hard Day's Night          1964       87
995                          Breakfast at Tiffany's          1961      115

      Genre  IMDB_Rating         Director            Star1  No_of_Votes  \
19   Comedy          8.6     Bong Joon Ho     Kang-ho Song       552778
26   Comedy          8.6  Roberto Benigni  Roberto Benigni       623629
51   Comedy          8.5  Charles Chaplin  Charles Chaplin       217881
52   Comedy          8.5  Charles Chaplin  Charles Chaplin       167839
64   Comedy          8.4  Rajkumar Hirani       Aamir Khan       344445
..      ...          ...              ...              ...          ...
977  Comedy          7.6     David Zucker   Leslie Nielsen       152871
978  Comedy          7.6      John Hughes     Steve Martin       124773
989  Comedy          7.6    Robert Altman    Elliott Gould        26337
994  Comedy          7.6   Richard Lester      John Lennon        40351
995  Comedy          7.6    Blake Edwards   Audrey Hepburn       166544

           Gross  Metascore
19    53367844.0       96.0
26    57598247.0       59.0
51      163245.0       96.0
52       19181.0       99.0
64     6532908.0       67.0
..           ...        ...
977   78756177.0       76.0
978   49530280.0       72.0
989     959000.0       87.0
994   13780024.0       96.0
995  679874270.0       76.0

[155 rows x 10 columns]
Crime

                Series_Title Released_Year  Runtime  Genre  IMDB_Rating  \
1              The Godfather          1972      175  Crime          9.2
3     The Godfather: Part II          1974      202  Crime          9.0
4               12 Angry Men          1957       96  Crime          9.0
6               Pulp Fiction          1994      154  Crime          8.9
22            Cidade de Deus          2002      130  Crime          8.6
..                       ...           ...      ...    ...          ...
958              Funny Games          1997      108  Crime          7.6
960                 Sleepers          1996      147  Crime          7.6
974  The Godfather: Part III          1990      162  Crime          7.6
980             Blood Simple          1984       99  Crime          7.6
999             The 39 Steps          1935       86  Crime          7.6

                 Director           Star1  No_of_Votes        Gross  Metascore
1    Francis Ford Coppola   Marlon Brando      1620367  134966411.0      100.0
3    Francis Ford Coppola       Al Pacino      1129952   57300000.0       90.0
4            Sidney Lumet     Henry Fonda       689845    4360000.0       96.0
6       Quentin Tarantino   John Travolta      1826188  107928762.0       94.0
22     Fernando Meirelles      Kátia Lund       699256    7563397.0       79.0
..                    ...             ...          ...          ...        ...
958        Michael Haneke  Susanne Lothar        65058  217345863.0       69.0
960        Barry Levinson  Robert De Niro       186734   49100000.0       49.0
974  Francis Ford Coppola       Al Pacino       359809   66666062.0       60.0
980             Joel Coen      Ethan Coen        87745    2150000.0       82.0
999      Alfred Hitchcock    Robert Donat        51853  302787539.0       93.0

[107 rows x 10 columns]
Drama

                        Series_Title Released_Year  Runtime  Genre  \
0           The Shawshank Redemption          1994      142  Drama
9                         Fight Club          1999      139  Drama
11                      Forrest Gump          1994      142  Drama
17   One Flew Over the Cuckoo's Nest          1975      133  Drama
20                   Soorarai Pottru          2020      153  Drama
..                               ...           ...      ...    ...
990                     Giù la testa          1971      157  Drama
993                           Blowup          1966      111  Drama
996                            Giant          1956      201  Drama
997            From Here to Eternity          1953      118  Drama
998                         Lifeboat          1944       97  Drama

     IMDB_Rating                Director              Star1  No_of_Votes  \
0            9.3          Frank Darabont        Tim Robbins      2343110
9            8.8           David Fincher          Brad Pitt      1854740
11           8.8         Robert Zemeckis          Tom Hanks      1809221
17           8.7            Milos Forman     Jack Nicholson       918088
20           8.6           Sudha Kongara             Suriya        54995
..           ...                     ...                ...          ...
990          7.6            Sergio Leone        Rod Steiger        30144
993          7.6  Michelangelo Antonioni     David Hemmings        56513
996          7.6          George Stevens   Elizabeth Taylor        34075
997          7.6          Fred Zinnemann     Burt Lancaster        43374
998          7.6        Alfred Hitchcock  Tallulah Bankhead        26471

           Gross  Metascore
0     28341469.0       80.0
9     37030102.0       66.0
11   330252182.0       82.0
17   112000000.0       83.0
20   556832648.0        NaN
..           ...        ...
990     696690.0       77.0
993  632532802.0       82.0
996  195217415.0       84.0
997   30500000.0       85.0
998  852142728.0       78.0

[289 rows x 10 columns]
Family

                            Series_Title Released_Year  Runtime   Genre  \
688           E.T. the Extra-Terrestrial          1982      115  Family
698  Willy Wonka & the Chocolate Factory          1971      100  Family

     IMDB_Rating          Director         Star1  No_of_Votes        Gross  \
688          7.8  Steven Spielberg  Henry Thomas       372490  435110554.0
698          7.8        Mel Stuart   Gene Wilder       178731    4000000.0

     Metascore
688       91.0
698       67.0
Fantasy

                     Series_Title Released_Year  Runtime    Genre  \
321  Das Cabinet des Dr. Caligari          1920       76  Fantasy
568                     Nosferatu          1922       94  Fantasy

     IMDB_Rating      Director          Star1  No_of_Votes        Gross  \
321          8.1  Robert Wiene  Werner Krauss        57428  337574718.0
568          7.9   F.W. Murnau    Max Schreck        88794  445151978.0

     Metascore
321        NaN
568        NaN
Film-Noir

           Series_Title Released_Year  Runtime      Genre  IMDB_Rating  \
309       The Third Man          1949      104  Film-Noir          8.1
456  The Maltese Falcon          1941      100  Film-Noir          8.0
712   Shadow of a Doubt          1943      108  Film-Noir          7.8

             Director            Star1  No_of_Votes        Gross  Metascore
309        Carol Reed     Orson Welles       158731     449191.0       97.0
456       John Huston  Humphrey Bogart       148928    2108060.0       96.0
712  Alfred Hitchcock    Teresa Wright        59556  123353292.0       94.0
Horror

                 Series_Title Released_Year  Runtime   Genre  IMDB_Rating  \
49                     Psycho          1960      109  Horror          8.5
75                      Alien          1979      117  Horror          8.4
271                 The Thing          1982      109  Horror          8.1
419              The Exorcist          1973      122  Horror          8.0
544  Night of the Living Dead          1968       96  Horror          7.9
707             The Innocents          1961      100  Horror          7.8
724                   Get Out          2017      104  Horror          7.7
844                 Halloween          1978       91  Horror          7.7
876         The Invisible Man          1933       71  Horror          7.7
932                       Saw          2004      103  Horror          7.6
948                The Others          2001      101  Horror          7.6

               Director             Star1  No_of_Votes        Gross  Metascore
49     Alfred Hitchcock   Anthony Perkins       604211   32000000.0       97.0
75         Ridley Scott  Sigourney Weaver       787806   78900000.0       89.0
271      John Carpenter      Kurt Russell       371271   13782838.0       57.0
419    William Friedkin     Ellen Burstyn       362393  232906145.0       81.0
544    George A. Romero       Duane Jones       116557      89029.0       89.0
707        Jack Clayton      Deborah Kerr        27007    2616000.0       88.0
724        Jordan Peele    Daniel Kaluuya       492851  176040665.0       85.0
844      John Carpenter  Donald Pleasence       233106   47000000.0       87.0
876         James Whale      Claude Rains        30683  298791505.0       87.0
932           James Wan        Cary Elwes       379020   56000369.0       46.0
948  Alejandro Amenábar     Nicole Kidman       337651   96522687.0       74.0
Mystery

          Series_Title Released_Year  Runtime    Genre  IMDB_Rating  \
69             Memento          2000      113  Mystery          8.4
81         Rear Window          1954      112  Mystery          8.4
119            Vertigo          1958      128  Mystery          8.3
145     Shutter Island          2010      138  Mystery          8.2
220            Kahaani          2012      122  Mystery          8.1
393     Twelve Monkeys          1995      129  Mystery          8.0
420             Sleuth          1972      138  Mystery          8.0
714  The Lady Vanishes          1938       96  Mystery          7.8
829          Spoorloos          1988      107  Mystery          7.7
899          El cuerpo          2012      112  Mystery          7.6
959          Dark City          1998      100  Mystery          7.6
961       Lost Highway          1997      134  Mystery          7.6

                 Director                     Star1  No_of_Votes        Gross  \
69      Christopher Nolan                Guy Pearce      1125712   25544867.0
81       Alfred Hitchcock             James Stewart       444074   36764313.0
119      Alfred Hitchcock             James Stewart       364368    3200000.0
145       Martin Scorsese         Leonardo DiCaprio      1129894  128012934.0
220           Sujoy Ghosh               Vidya Balan        57806    1035953.0
393         Terry Gilliam              Bruce Willis       578443   57141459.0
420  Joseph L. Mankiewicz          Laurence Olivier        44748    4081254.0
714      Alfred Hitchcock         Margaret Lockwood        47400  474203697.0
829        George Sluizer  Bernard-Pierre Donnadieu        33982  367916835.0
899           Oriol Paulo             Jose Coronado        57549  140340673.0
959           Alex Proyas              Rufus Sewell       187927   14378331.0
961           David Lynch              Bill Pullman       131101    3796699.0

     Metascore
69        80.0
81       100.0
119      100.0
145       63.0
220        NaN
393       74.0
420        NaN
714       98.0
829        NaN
899        NaN
959       66.0
961       52.0
Thriller

        Series_Title Released_Year  Runtime     Genre  IMDB_Rating  \
700  Wait Until Dark          1967      108  Thriller          7.8

          Director           Star1  No_of_Votes       Gross  Metascore

### Find the highest rated movie of each genre

In [52]:
for group, data in grouped_data:
    print(f'Highest rated movie of {group} genre is {data.sort_values(by='IMDB_Rating', ascending= False).head(1)['Series_Title']}')

Highest rated movie of Action genre is 2    The Dark Knight
Name: Series_Title, dtype: object
Highest rated movie of Adventure genre is 21    Interstellar
Name: Series_Title, dtype: object
Highest rated movie of Animation genre is 23    Sen to Chihiro no kamikakushi
Name: Series_Title, dtype: object
Highest rated movie of Biography genre is 7    Schindler's List
Name: Series_Title, dtype: object
Highest rated movie of Comedy genre is 19    Gisaengchung
Name: Series_Title, dtype: object
Highest rated movie of Crime genre is 1    The Godfather
Name: Series_Title, dtype: object
Highest rated movie of Drama genre is 0    The Shawshank Redemption
Name: Series_Title, dtype: object
Highest rated movie of Family genre is 688    E.T. the Extra-Terrestrial
Name: Series_Title, dtype: object
Highest rated movie of Fantasy genre is 321    Das Cabinet des Dr. Caligari
Name: Series_Title, dtype: object
Highest rated movie of Film-Noir genre is 309    The Third Man
Name: Series_Title, dtype: object
Highest rated movie of Horror genre is 49    Psycho
Name: Series_Title, dtype: object
Highest rated movie of Mystery genre is 69    Memento
Name: Series_Title, dtype: object
Highest rated movie of Thriller genre is 700    Wait Until Dark
Name: Series_Title, dtype: object
Highest rated movie of Western genre is 12    Il buono, il brutto, il cattivo
Name: Series_Title, dtype: object

### .groupby().apply() 

It is used to apply a custom function to each group and combine the results.

- **Syntax**

        df.groupby(by).apply(func)

| Parameter | Description                                              | Default | Possible Values                          |
|-----------|----------------------------------------------------------|---------|------------------------------------------|
| by        | Column(s) to group by                                    | —       | label, list                              |
| func      | Function to apply to each group                          | —       | function, lambda                         |
| axis      | Axis along which function is applied                     | 0       | 0 (rows), 1 (columns)                    |

---

#### Key Points

- Applies **custom logic** to each group  
- More flexible than `.agg()` and `.transform()`  
- Can return **DataFrame, Series, or scalar**  
- Slower compared to built-in aggregations

### Find number of movies starting with A for each group

In [53]:
def A_start(group):
    return group['Series_Title'].str.startswith('A').sum()

In [54]:
grouped_data.apply(A_start)

/var/folders/94/2_5s7zqj0cqd50nz6b9khlxh0000gp/T/ipykernel_21350/2496241426.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data.apply(A_start)

Genre
Action       10
Adventure     2
Animation     2
Biography     9
Comedy       14
Crime         4
Drama        21
Family        0
Fantasy       0
Film-Noir     0
Horror        1
Mystery       0
Thriller      0
Western       0
dtype: int64

In [55]:
for group, data in grouped_data:
    print(group, data['Series_Title'].str.startswith('A').sum())

Action 10
Adventure 2
Animation 2
Biography 9
Comedy 14
Crime 4
Drama 21
Family 0
Fantasy 0
Film-Noir 0
Horror 1
Mystery 0
Thriller 0
Western 0

### Find ranking of each movie in the group according to IMDB score

### .rank() 

It is used to assign ranks to values in a Series or DataFrame.

- **Syntax**

        df.rank(axis=0, method='average', ascending=True)

| Parameter   | Description                                              | Default     | Possible Values                                      |
|-------------|----------------------------------------------------------|-------------|------------------------------------------------------|
| axis        | Axis along which ranking is applied                      | 0           | 0 (index), 1 (columns)                               |
| method      | Method to assign ranks in case of ties                   | 'average'   | 'average', 'min', 'max', 'first', 'dense'            |
| ascending   | Rank order                                               | True        | True, False                                          |
| na_option   | How to handle NaN values                                 | 'keep'      | 'keep', 'top', 'bottom'                              |
| pct         | Return ranks as percentage                               | False       | True, False                                          |
| numeric_only| Include only numeric data (DataFrame)                    | None        | True, False                                          |

---

#### Key Points

- Assigns ranks to values (1 = smallest by default)  
- Handles ties using different methods  
- Can rank across rows or columns

In [56]:
def ranking_in_group(group):
    group['ranking_in_group'] = group['IMDB_Rating'].rank(method = 'min', ascending = False)
    return group

In [57]:
grouped_data.apply(ranking_in_group)

/var/folders/94/2_5s7zqj0cqd50nz6b9khlxh0000gp/T/ipykernel_21350/2998522937.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data.apply(ranking_in_group)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              ranking_in_group
Genre
Action   2                 1.0
         5                 2.0
         8                 3.0
         10                3.0
         13                5.0
...                        ...
Thriller 700               1.0
Western  12                1.0
         48                2.0
         115               3.0
         691               4.0

[1000 rows x 11 columns]

### Find the normalized IMDB rating group wise

In [63]:
def normalize(group):
    group['normalized_rating'] = (group['IMDB_Rating']-group['IMDB_Rating'].min())/(group['IMDB_Rating'].max()-group['IMDB_Rating'].min())
    return group

In [64]:
grouped_data.apply(normalize)

/var/folders/94/2_5s7zqj0cqd50nz6b9khlxh0000gp/T/ipykernel_21350/3580493208.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped_data.apply(normalize)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              normalized_rating
Genre
Action   2             1.000000
         5             0.928571
         8             0.857143
         10            0.857143
         13            0.785714
...                         ...
Thriller 700                NaN
Western  12            1.000000
         48            0.700000
         115           0.500000
         691           0.000000

[1000 rows x 11 columns]

In [65]:
imdb_data.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

### Find the most earning actor-director duo

In [66]:
duo_grouped_data = imdb_data.groupby(by=['Director', 'Star1'], dropna=False)

In [68]:
duo_grouped_data.size()

Director             Star1
Aamir Khan           Amole Gupte       1
Aaron Sorkin         Eddie Redmayne    1
Abdellatif Kechiche  Léa Seydoux       1
Abhishek Chaubey     Shahid Kapoor     1
Abhishek Kapoor      Amit Sadh         1
                                      ..
Zaza Urushadze       Lembit Ulfsak     1
Zoya Akhtar          Hrithik Roshan    1
                     Vijay Varma       1
Çagan Irmak          Çetin Tekindor    1
Ömer Faruk Sorak     Cem Yilmaz        1
Length: 898, dtype: int64

In [69]:
# if we want to retrive any group

duo_grouped_data.get_group(('Aaron Sorkin', 'Eddie Redmayne'))

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
612,The Trial of the Chicago 7,2020,129,Drama,7.8,Aaron Sorkin,Eddie Redmayne,89896,853090410.0,77.0

In [77]:
duo_grouped_data['Gross']

In [78]:
duo_grouped_data['Gross'].sum()

Director             Star1
Aamir Khan           Amole Gupte         1223869.0
Aaron Sorkin         Eddie Redmayne    853090410.0
Abdellatif Kechiche  Léa Seydoux         2199675.0
Abhishek Chaubey     Shahid Kapoor     218428303.0
Abhishek Kapoor      Amit Sadh           1122527.0
                                          ...
Zaza Urushadze       Lembit Ulfsak        144501.0
Zoya Akhtar          Hrithik Roshan      3108485.0
                     Vijay Varma         5566534.0
Çagan Irmak          Çetin Tekindor    461855363.0
Ömer Faruk Sorak     Cem Yilmaz        196206077.0
Name: Gross, Length: 898, dtype: float64

In [79]:
duo_grouped_data['Gross'].sum().sort_values(ascending=False)

Director              Star1
Akira Kurosawa        Toshirô Mifune     2.999877e+09
Anthony Russo         Joe Russo          2.205039e+09
Billy Wilder          William Holden     1.286779e+09
Christopher Nolan     Christian Bale     1.242940e+09
Werner Herzog         Klaus Kinski       1.124605e+09
                                             ...
Jeong-beom Lee        Won Bin            6.460000e+03
Shane Meadows         Paddy Considine    6.013000e+03
Jaco Van Dormael      Jared Leto         3.600000e+03
Thomas Jahn           Til Schweiger      3.296000e+03
Anders Thomas Jensen  Ulrich Thomsen     1.305000e+03
Name: Gross, Length: 898, dtype: float64

In [80]:
duo_grouped_data['Gross'].sum().sort_values(ascending=False).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

### Find the best(in terms of metascore(avg)) actor-genre combo

In [81]:
grouped = imdb_data.groupby(by=['Star1', 'Genre'])

In [82]:
grouped['Metascore'].head(5)

0       80.0
1      100.0
2       84.0
3       90.0
4       96.0
       ...
995     76.0
996     84.0
997     85.0
998     78.0
999     93.0
Name: Metascore, Length: 999, dtype: float64

In [83]:
grouped.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [84]:
def avg(group):
    return group['Metascore'].sum()/group['Metascore'].count()

In [85]:
grouped.apply(avg)

/var/folders/94/2_5s7zqj0cqd50nz6b9khlxh0000gp/T/ipykernel_21350/801600635.py:2: RuntimeWarning: invalid value encountered in scalar divide
  return group['Metascore'].sum()/group['Metascore'].count()
/var/folders/94/2_5s7zqj0cqd50nz6b9khlxh0000gp/T/ipykernel_21350/3920130205.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped.apply(avg)

Star1                 Genre
Aamir Khan            Action        NaN
                      Adventure    84.0
                      Comedy       67.0
Aaron Taylor-Johnson  Action       66.0
Abhay Deol            Drama         NaN
                                   ...
Zbigniew Zamachowski  Comedy       88.0
Zooey Deschanel       Comedy       76.0
Çetin Tekindor        Drama         NaN
Éric Toledano         Biography    57.0
Ömer Faruk Sorak      Comedy        NaN
Length: 829, dtype: float64

In [89]:
grouped.apply(avg).sort_values(ascending=False)

/var/folders/94/2_5s7zqj0cqd50nz6b9khlxh0000gp/T/ipykernel_21350/801600635.py:2: RuntimeWarning: invalid value encountered in scalar divide
  return group['Metascore'].sum()/group['Metascore'].count()
/var/folders/94/2_5s7zqj0cqd50nz6b9khlxh0000gp/T/ipykernel_21350/3604890213.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped.apply(avg).sort_values(ascending=False)

Star1             Genre
Ellar Coltrane    Drama      100.0
Humphrey Bogart   Drama      100.0
James Stewart     Mystery    100.0
Bertil Guve       Drama      100.0
Orson Welles      Drama      100.0
                             ...
William Holden    Drama        NaN
Won Bin           Action       NaN
Yash              Action       NaN
Çetin Tekindor    Drama        NaN
Ömer Faruk Sorak  Comedy       NaN
Length: 829, dtype: float64

In [90]:
grouped.apply(avg).sort_values(ascending=False).head(1)

/var/folders/94/2_5s7zqj0cqd50nz6b9khlxh0000gp/T/ipykernel_21350/801600635.py:2: RuntimeWarning: invalid value encountered in scalar divide
  return group['Metascore'].sum()/group['Metascore'].count()
/var/folders/94/2_5s7zqj0cqd50nz6b9khlxh0000gp/T/ipykernel_21350/3182152783.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped.apply(avg).sort_values(ascending=False).head(1)

Star1           Genre
Ellar Coltrane  Drama    100.0
dtype: float64

In [91]:
grouped.apply(avg).sort_values(ascending=False).head(1).reset_index()

/var/folders/94/2_5s7zqj0cqd50nz6b9khlxh0000gp/T/ipykernel_21350/801600635.py:2: RuntimeWarning: invalid value encountered in scalar divide
  return group['Metascore'].sum()/group['Metascore'].count()
/var/folders/94/2_5s7zqj0cqd50nz6b9khlxh0000gp/T/ipykernel_21350/4253286070.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  grouped.apply(avg).sort_values(ascending=False).head(1).reset_index()

            Star1  Genre      0
0  Ellar Coltrane  Drama  100.0

### Find the top 10 batsman in terms of runs

In [92]:
delivery_data.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [93]:
grouped_on_batsman = delivery_data.groupby(by=['batsman'], dropna=False)

In [96]:
grouped_on_batsman['batsman_runs'].sum()

batsman
A Ashish Reddy     280
A Chandila           4
A Chopra            53
A Choudhary         25
A Dananjaya          4
                  ...
YV Takawale        192
Yashpal Singh       47
Younis Khan          3
Yuvraj Singh      2765
Z Khan             117
Name: batsman_runs, Length: 516, dtype: int64

In [97]:
grouped_on_batsman['batsman_runs'].sum().sort_values(ascending=False)

batsman
V Kohli        5434
SK Raina       5415
RG Sharma      4914
DA Warner      4741
S Dhawan       4632
               ...
IC Pandey         0
J Denly           0
P Raj             0
Sunny Gupta       0
L Ablish          0
Name: batsman_runs, Length: 516, dtype: int64

In [98]:
grouped_on_batsman['batsman_runs'].sum().sort_values(ascending=False).head(10)

batsman
V Kohli           5434
SK Raina          5415
RG Sharma         4914
DA Warner         4741
S Dhawan          4632
CH Gayle          4560
MS Dhoni          4477
RV Uthappa        4446
AB de Villiers    4428
G Gambhir         4223
Name: batsman_runs, dtype: int64

### Find the batsman with max number of sixes

In [99]:
delivery_data.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [101]:
delivery_data[delivery_data['batsman_runs']==6]

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
47,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,8,4,MC Henriques,S Dhawan,TM Head,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
75,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,13,2,Yuvraj Singh,MC Henriques,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
89,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,3,Yuvraj Singh,MC Henriques,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
91,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,15,5,MC Henriques,Yuvraj Singh,S Aravind,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
178987,11415,2,Chennai Super Kings,Mumbai Indians,6,4,SR Watson,SK Raina,SL Malinga,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179048,11415,2,Chennai Super Kings,Mumbai Indians,16,1,DJ Bravo,SR Watson,SL Malinga,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179061,11415,2,Chennai Super Kings,Mumbai Indians,18,2,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179062,11415,2,Chennai Super Kings,Mumbai Indians,18,3,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179063,11415,2,Chennai Super Kings,Mumbai Indians,18,4,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN

In [102]:
delivery_data[delivery_data['batsman_runs']==6].groupby(by=['batsman'], dropna=False)

In [107]:
six_hitting_grouped = delivery_data[delivery_data['batsman_runs']==6].groupby(by=['batsman'], dropna=False)

In [108]:
six_hitting_grouped

In [109]:
six_hitting_grouped['batsman_runs'].count()

batsman
A Ashish Reddy      15
A Choudhary          1
A Flintoff           2
A Hales              6
A Mishra             5
                  ...
Y Venugopal Rao     37
YK Pathan          161
YV Takawale          3
Yuvraj Singh       149
Z Khan               2
Name: batsman_runs, Length: 336, dtype: int64

In [111]:
six_hitting_grouped['batsman_runs'].count().sort_values(ascending=False)

batsman
CH Gayle          327
AB de Villiers    214
MS Dhoni          207
SK Raina          195
RG Sharma         194
                 ...
CK Langeveldt       1
JDS Neesham         1
SK Trivedi          1
D Shorey            1
MN van Wyk          1
Name: batsman_runs, Length: 336, dtype: int64

In [112]:
six_hitting_grouped['batsman_runs'].count().sort_values(ascending=False).head(1)

batsman
CH Gayle    327
Name: batsman_runs, dtype: int64

### Find the batsman with most number of 4's and 6's in last 5 overs

In [114]:
last_5_over_details = delivery_data[delivery_data['over']>=16]

In [115]:
last_5_over_details

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
93,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,1,MC Henriques,Yuvraj Singh,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
94,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,2,MC Henriques,Yuvraj Singh,YS Chahal,0,...,0,0,0,0,0,0,0,MC Henriques,caught,Sachin Baby
95,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,3,Yuvraj Singh,DJ Hooda,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
96,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,4,DJ Hooda,Yuvraj Singh,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
97,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,5,Yuvraj Singh,DJ Hooda,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [117]:
last_5_over_4_and_6 = last_5_over_details[(last_5_over_details['batsman_runs']==4) | (last_5_over_details['batsman_runs']==6)]

In [119]:
last_5_over_4_and_6

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
101,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,17,3,Yuvraj Singh,DJ Hooda,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
105,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,18,1,DJ Hooda,Yuvraj Singh,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
109,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,18,5,Yuvraj Singh,DJ Hooda,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
114,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,19,2,Yuvraj Singh,DJ Hooda,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
115,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,19,3,Yuvraj Singh,DJ Hooda,TS Mills,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179052,11415,2,Chennai Super Kings,Mumbai Indians,16,5,SR Watson,DJ Bravo,SL Malinga,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
179061,11415,2,Chennai Super Kings,Mumbai Indians,18,2,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179062,11415,2,Chennai Super Kings,Mumbai Indians,18,3,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179063,11415,2,Chennai Super Kings,Mumbai Indians,18,4,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179071,11415,2,Chennai Super Kings,Mumbai Indians,19,6,RA Jadeja,SR Watson,JJ Bumrah,0,...,4,0,0,0,4,4,8,NaN,NaN,NaN

In [120]:
hitting_4_and_6_group = last_5_over_4_and_6.groupby(by=['batsman'], dropna=False)

In [121]:
hitting_4_and_6_group['batsman_runs'].count()

batsman
A Ashish Reddy     23
A Choudhary         2
A Flintoff          3
A Joseph            2
A Kumble            3
                 ...
YK Pathan         149
YV Takawale         5
Yashpal Singh       3
Yuvraj Singh      130
Z Khan             13
Name: batsman_runs, Length: 360, dtype: int64

In [122]:
hitting_4_and_6_group['batsman_runs'].count().sort_values(ascending=False)

batsman
MS Dhoni          340
AB de Villiers    208
RG Sharma         208
KA Pollard        206
V Kohli           160
                 ...
KC Cariappa         1
Shivam Sharma       1
Shoaib Malik        1
T Curran            1
KJ Abbott           1
Name: batsman_runs, Length: 360, dtype: int64

In [123]:
hitting_4_and_6_group['batsman_runs'].count().sort_values(ascending=False).head(1)

batsman
MS Dhoni    340
Name: batsman_runs, dtype: int64

### Find Virat Kohli record against all teams

In [131]:
delivery_data.sample(10)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
94597,400,1,Kings XI Punjab,Kolkata Knight Riders,3,6,Mandeep Singh,AC Gilchrist,L Balaji,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
112545,475,2,Kings XI Punjab,Royal Challengers Bangalore,1,3,CA Pujara,V Sehwag,MA Starc,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
62279,263,2,Royal Challengers Bangalore,Delhi Daredevils,13,1,CA Pujara,SS Tiwary,Y Nagar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
117821,497,2,Kolkata Knight Riders,Mumbai Indians,2,5,G Gambhir,RV Uthappa,JJ Bumrah,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
73874,314,1,Rajasthan Royals,Kolkata Knight Riders,10,6,AL Menaria,BJ Hodge,SP Narine,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
148992,630,2,Gujarat Lions,Mumbai Indians,17,4,RA Jadeja,DR Smith,JJ Bumrah,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
154575,7911,1,Kolkata Knight Riders,Kings XI Punjab,16,6,KD Karthik,AD Russell,AJ Tye,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
115451,487,1,Sunrisers Hyderabad,Rajasthan Royals,20,2,IK Pathan,DW Steyn,JP Faulkner,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
89755,379,2,Mumbai Indians,Chennai Super Kings,20,4,SL Malinga,DS Kulkarni,RA Jadeja,0,...,0,0,0,0,0,0,0,SL Malinga,bowled,NaN
89944,380,2,Delhi Daredevils,Chennai Super Kings,10,6,AD Russell,DPMD Jayawardene,SB Jakati,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN

In [136]:
virat_kohli_data = delivery_data[delivery_data['batsman'] == 'V Kohli']

In [137]:
virat_kohli_data.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
2590,12,1,Royal Challengers Bangalore,Mumbai Indians,1,2,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,1,1,NaN,NaN,NaN
2591,12,1,Royal Challengers Bangalore,Mumbai Indians,1,3,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2593,12,1,Royal Challengers Bangalore,Mumbai Indians,1,5,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2594,12,1,Royal Challengers Bangalore,Mumbai Indians,1,6,V Kohli,CH Gayle,TG Southee,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
2597,12,1,Royal Challengers Bangalore,Mumbai Indians,2,1,V Kohli,CH Gayle,Harbhajan Singh,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN

In [138]:
virat_kohli_run_against_team = virat_kohli_data.groupby(by=['bowling_team'], dropna=False)

In [140]:
virat_kohli_run_against_team['batsman_runs'].sum()

bowling_team
Chennai Super Kings        749
Deccan Chargers            306
Delhi Capitals              66
Delhi Daredevils           763
Gujarat Lions              283
Kings XI Punjab            636
Kochi Tuskers Kerala        50
Kolkata Knight Riders      675
Mumbai Indians             628
Pune Warriors              128
Rajasthan Royals           370
Rising Pune Supergiant      83
Rising Pune Supergiants    188
Sunrisers Hyderabad        509
Name: batsman_runs, dtype: int64

In [141]:
virat_kohli_run_against_team['batsman_runs'].sum().sort_values(ascending=False)

bowling_team
Delhi Daredevils           763
Chennai Super Kings        749
Kolkata Knight Riders      675
Kings XI Punjab            636
Mumbai Indians             628
Sunrisers Hyderabad        509
Rajasthan Royals           370
Deccan Chargers            306
Gujarat Lions              283
Rising Pune Supergiants    188
Pune Warriors              128
Rising Pune Supergiant      83
Delhi Capitals              66
Kochi Tuskers Kerala        50
Name: batsman_runs, dtype: int64

### Create a function that can return the highest score of any batsman

In [144]:
def highest_score(name):
    player_data = delivery_data[delivery_data['batsman'] == name]
    player_match_detail = player_data.groupby(by=['match_id'], dropna = False)
    return player_match_detail['batsman_runs'].sum().max()

In [145]:
highest_score('V Kohli')

np.int64(113)

In [146]:
highest_score('CH Gayle')

np.int64(175)